[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test* *Test
python_functions = test_*
markers =
    ui: UI-тесты для проверки интерфейса
    api: API-тесты для проверки эндпоинтов
addopts = --strict-markers -v
